//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZsmart
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Biblioteca
    {
        [Key]
        public int id { get; set; }

        [Required(ErrorMessage = "El título es obligatorio.")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "El título solo debe contener letras y espacios.")]
        public string titulo { get; set; }

        public int autor_id { get; set; }
    
        public virtual Autores Autores { get; set; }
    }
}
